CREATE TABLE [dbo].[ORGM_ORDER_HD] (
    [Id]             UNIQUEIDENTIFIER NOT NULL,
    [ORGM_ORDER_HId] UNIQUEIDENTIFIER NOT NULL,
    [ORGM_DATA_HDId] UNIQUEIDENTIFIER NOT NULL,
    [Qty]            INT              NOT NULL,
    [ProductId]      UNIQUEIDENTIFIER DEFAULT ('50e4c569-8198-4093-76e5-08d6b7fc75a2') NOT NULL,
    [CurrencyId]     UNIQUEIDENTIFIER DEFAULT ('fadede5d-1c91-4d95-92e4-f447ea6edade') NOT NULL,
    CONSTRAINT [PK_ORGM_ORDER_HD] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ORGM_ORDER_HD_Currency_CurrencyId] FOREIGN KEY ([CurrencyId]) REFERENCES [dbo].[Currency] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_ORGM_ORDER_HD_ORGM_DATA_HD_ORGM_DATA_HDId] FOREIGN KEY ([ORGM_DATA_HDId]) REFERENCES [dbo].[ORGM_DATA_HD] ([Id]),
    CONSTRAINT [FK_ORGM_ORDER_HD_ORGM_ORDER_H_ORGM_ORDER_HId] FOREIGN KEY ([ORGM_ORDER_HId]) REFERENCES [dbo].[ORGM_ORDER_H] ([Id]),
    CONSTRAINT [FK_ORGM_ORDER_HD_Product_ProductId] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[Product] ([Id])
);


GO
CREATE NONCLUSTERED INDEX [IX_ORGM_ORDER_HD_ORGM_DATA_HDId]
    ON [dbo].[ORGM_ORDER_HD]([ORGM_DATA_HDId] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_ORGM_ORDER_HD_ORGM_ORDER_HId]
    ON [dbo].[ORGM_ORDER_HD]([ORGM_ORDER_HId] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_ORGM_ORDER_HD_ProductId]
    ON [dbo].[ORGM_ORDER_HD]([ProductId] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_ORGM_ORDER_HD_CurrencyId]
    ON [dbo].[ORGM_ORDER_HD]([CurrencyId] ASC);

